### ISSUE TITLE
Alarm server fails to handle PV value update

### ISSUE THREAD

**Issue by sasaki77** [ControlSystemStudio/phoebus#1905] opened 2021-05-10 01:29 UTC
I'm trying to evaluate alarm server performance. The alarm server is configured to monitor 50000 PVs. There are 400 state changes per 40 seconds, 200 PVs are changed to MINOR state and other 200 PVs are changed to OK state.

I got following error when I started the alarm server. Same errors occurred for several PVs.
The alarm server can't update alarm state of the PV that raised the error. In this case, Alarm server ignores the state changes of `/Accelerator/TEST/Alarm13811`.

Does the alarm server refer the alarm tree PV before completing its initialization to maximize parent severity?

```
io.reactivex.rxjava3.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | java.lang.RuntimeException: /Accelerator/TEST/Alarm13811 failed to handle update VDouble[1.0, MINOR(NONE) - HIGH_ALARM, 2021-04-28T02:38:52.963714095Z]
	at io.reactivex.rxjava3.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:717)
	at io.reactivex.rxjava3.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:714)
	at io.reactivex.rxjava3.internal.subscribers.LambdaSubscriber.onError(LambdaSubscriber.java:79)
	at io.reactivex.rxjava3.internal.subscribers.LambdaSubscriber.onNext(LambdaSubscriber.java:69)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableCreate$BufferAsyncEmitter.drain(FlowableCreate.java:550)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableCreate$BufferAsyncEmitter.onNext(FlowableCreate.java:478)
	at org.phoebus.pv.ValueEventHandler$Subscription.update(ValueEventHandler.java:38)
	at org.phoebus.pv.PV.notifyListenersOfValue(PV.java:311)
	at org.phoebus.pv.ca.JCA_PV.monitorChanged(JCA_PV.java:383)
	at gov.aps.jca.event.DirectEventDispatcher.dispatch(DirectEventDispatcher.java:84)
	at com.cosylab.epics.caj.CAJMonitor.monitorChanged(CAJMonitor.java:248)
	at gov.aps.jca.event.DirectEventDispatcher.dispatch(DirectEventDispatcher.java:155)
	at com.cosylab.epics.caj.impl.requests.EventAddRequest.response(EventAddRequest.java:213)
	at com.cosylab.epics.caj.impl.handlers.EventAddResponse.internalHandleResponse(EventAddResponse.java:61)
	at com.cosylab.epics.caj.impl.handlers.AbstractCAResponseHandler.handleResponse(AbstractCAResponseHandler.java:110)
	at com.cosylab.epics.caj.impl.CAResponseHandler.handleResponse(CAResponseHandler.java:139)
	at com.cosylab.epics.caj.impl.CATransport.processRead(CATransport.java:549)
	at com.cosylab.epics.caj.impl.CATransport.processRead(CATransport.java:431)
	at com.cosylab.epics.caj.impl.CATransport.handleEvent(CATransport.java:369)
	at com.cosylab.epics.caj.impl.reactor.lf.LeaderFollowersHandler.handleEvent(LeaderFollowersHandler.java:77)
	at com.cosylab.epics.caj.impl.reactor.Reactor.processInternal(Reactor.java:404)
	at com.cosylab.epics.caj.impl.reactor.Reactor.process(Reactor.java:288)
	at com.cosylab.epics.caj.impl.reactor.lf.LeaderFollowersHandler.run(LeaderFollowersHandler.java:91)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.RuntimeException: /Accelerator/TEST/Alarm13811 failed to handle update VDouble[1.0, MINOR(NONE) - HIGH_ALARM, 2021-04-28T02:38:52.963714095Z]
	at org.phoebus.applications.alarm.server.AlarmServerPV.handleValueUpdate(AlarmServerPV.java:415)
	at io.reactivex.rxjava3.internal.subscribers.LambdaSubscriber.onNext(LambdaSubscriber.java:65)
	... 22 more
Caused by: java.lang.RuntimeException: /Accelerator/TEST failed to maximize severity
	at org.phoebus.applications.alarm.server.AlarmServerNode.maximizeSeverity(AlarmServerNode.java:101)
	at org.phoebus.applications.alarm.server.AlarmServerPV$1.alarmStateChanged(AlarmServerPV.java:116)
	at org.phoebus.applications.alarm.server.AlarmLogic.updateState(AlarmLogic.java:422)
	at org.phoebus.applications.alarm.server.AlarmLogic.computeNewState(AlarmLogic.java:360)
	at org.phoebus.applications.alarm.server.AlarmServerPV.handleValueUpdate(AlarmServerPV.java:410)
	... 23 more
Caused by: java.lang.NullPointerException: /Accelerator/TEST/Alarm24933 logic == null
	at org.phoebus.applications.alarm.server.AlarmServerPV.getState(AlarmServerPV.java:134)
	at org.phoebus.applications.alarm.server.AlarmServerPV.getState(AlarmServerPV.java:50)
	at org.phoebus.applications.alarm.server.AlarmServerNode.maximizeSeverity(AlarmServerNode.java:74)
	... 27 more
```

**Comment by kasemir** [comment] 2021-05-10 11:59
> I got following error when I started the alarm server.

What did you do exactly? Start the alarm server, when the configuration was already in place?
Or import the configuration while the alarm server was running?
Or re-start a running alarm server?

Does the error happen quite regularly when you try this, maybe with different PVs, but otherwise reproducible?
If so, can you try to add `synchronized` to the `AlarmServerPV` constructor and the `getState()` method? That might not be the best solution, but should avoid the specific issue for now.

**Comment by sasaki77** [comment] 2021-05-11 03:58
> What did you do exactly? Start the alarm server, when the configuration was already in place?
> Or import the configuration while the alarm server was running?
> Or re-start a running alarm server?

First of all, I imported the configuration while the alarm server was stopping.
And then, I started the alarm server.

> Does the error happen quite regularly when you try this, maybe with different PVs, but otherwise reproducible?

Yes. The errors regularly happen with different PVs.

**Comment by sasaki77** [comment] 2021-05-11 03:59
> How did you create your test setup? I assume your `Alarm12345` type of PVs run on some softIoc with a *.db file that you generated with some script.

As you thought, "*.db" file is generated with the script.
But, all PVs run on one softIoc.

**Comment by sasaki77** [comment] 2021-05-11 04:03
I built and ran the alarm server with your pull request #1906.
The alarm server can run without errors now.

Thank you for quick fixing.

**Comment by kasemir** [comment] 2021-05-11 12:10
Our ~12 hour time difference works out great, I was able to work on this while you were resting, and then you were able to test the update while I was asleep ;-) 
Good to see that you were able to reproduce the issue several times.  @tanviash this should be exactly the same issue that you've been seeing. While I haven't seen that here because of different timing, different number and types of PVs, the stack traces make perfect sense and should be fixed in the pull request.
Excellent news that the changes indeed seem to work as intended, and thanks a lot for testing that so quickly.

**Closed** 2021-05-11 23:33 UTC
